package edu.msa.intouch.util

enum class BackendApiCallTypeEnum {
    CREATE_CLIENT,
    GET_CLIENT_BY_ID,
    CREATE_CONNECTION,
    GET_ALL_CONNECTIONS_BY_STATUS,
    GET_ALL_CONNECTION_REQUESTS_BY_STATUS,
    UPDATE_CONNECTION_STATUS,
    DELETE_CONNECTION_REQUEST
}